// Digital-nomad / remote-work visa programmes.
//
// Lives here rather than in the frontend so the server-rendered /digital-nomad
// page and the React page read the SAME records. These are visa facts: a second
// copy would drift, and a drifted income threshold is a wrong answer.
export interface DigitalNomadVisa {
  country: string;
  code: string;
  flag: string;
  region: string;
  visaName: string;
  minMonthlyIncome: string | null;
  minAnnualIncome: string | null;
  govFee: string | null;
  duration: string;
  renewable: boolean;
  taxBenefits: boolean;
  businessRequired: boolean;
  insuranceRequired: boolean;
  notes: string;
  officialUrl: string;
  /** "ended" for programmes a government has closed — kept for searchers, excluded from the directory count. */
  status: "open" | "ended";
  /** Why and when the programme closed. Present only when status is "ended". */
  endedNote?: string;
  /** Official page every figure above was read from. null = not yet re-checked against source. */
  source: string | null;
  /** ISO date that check was made. */
  verifiedOn: string | null;
}

const ALL_NOMAD_VISAS: DigitalNomadVisa[] = [
  // EUROPE
  {
    country: "Portugal", code: "PT", flag: "🇵🇹", region: "Europe",
    visaName: "D9 Digital Nomad Visa",
    minMonthlyIncome: "€3,680",
    minAnnualIncome: null,
    govFee: "€110",
    duration: "1 year",
    renewable: true,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Officially the residence visa for remote professional activity (D9). D8 is a different visa — family accompaniment. The threshold is four times the guaranteed minimum monthly wage, €920 in 2026, so it moves every January. The visa runs a year and leads to a residence permit issued by AIMA, whose length we could not confirm from an official source.",
    officialUrl: "https://vistos.mne.gov.pt/",
    status: "open",
    source: "https://vistos.mne.gov.pt/pt/vistos-nacionais/informacao-geral/emolumentos",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Spain", code: "ES", flag: "🇪🇸", region: "Europe",
    visaName: "Telework (Nomad) Visa",
    minMonthlyIncome: "€2,442",
    minAnnualIncome: null,
    govFee: null,
    duration: "1 year (abroad) / 3 years (in-country)",
    renewable: true,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Threshold is 200% of the Spanish minimum wage (SMI) and moves with it — €1,221/month in 2026. The consular fee is set by reciprocity and charged in local currency, so no single euro figure is official. Beckham Law: flat 24% tax rate for up to 6 years.",
    officialUrl: "https://www.exteriores.gob.es/",
    status: "open",
    source: "https://www.boe.es/buscar/act.php?id=BOE-A-2026-3815",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Greece", code: "GR", flag: "🇬🇷", region: "Europe",
    visaName: "Digital Nomad Visa",
    minMonthlyIncome: "€3,500",
    minAnnualIncome: null,
    govFee: "€1,000",
    duration: "12 months, then a 2-year residence permit",
    renewable: true,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "National visa for 12 months (residence title Z.1), then a 2-year residence permit (type I.8) under art. 68 §4 of Law 5038/2023. 50% income tax reduction for 2 years if staying as tax resident.",
    officialUrl: "https://migration.gov.gr/",
    status: "open",
    source: "https://migration.gov.gr/en/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Croatia", code: "HR", flag: "🇭🇷", region: "Europe",
    visaName: "Digital Nomad Permit",
    minMonthlyIncome: "€3,622.50",
    minAnnualIncome: "€43,470",
    govFee: "€87.59 at a police station",
    duration: "Up to 18 months",
    renewable: true,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Means test is 2.5 average monthly net Croatian salaries, so it moves each year; €65,205 is required for the full 18 months. Extension is possible only up to the 18-month maximum, after which a new application needs a 6-month gap. Tax exempt during stay — no local income tax.",
    officialUrl: "https://mup.gov.hr/aliens-281621/temporary-stay-of-digital-nomads-286853/286853",
    status: "open",
    source: "https://mup.gov.hr/aliens-281621/temporary-stay-of-digital-nomads-286853/286853",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Italy", code: "IT", flag: "🇮🇹", region: "Europe",
    visaName: "Remote Worker Visa",
    minMonthlyIncome: null,
    minAnnualIncome: "€25,500",
    govFee: "~€116",
    duration: "1 year",
    renewable: true,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Three times the annual exemption from healthcare cost-sharing (€8,500). Stated annually only. Free Schengen Area travel.",
    officialUrl: "https://vistoperitalia.esteri.it/",
    status: "open",
    source: "https://vistoperitalia.esteri.it/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Germany", code: "DE", flag: "🇩🇪", region: "Europe",
    visaName: "Freelancer Visa (§21 AufenthG)",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: "€100",
    duration: "1–3 years",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "No fixed minimum income under §21 AufenthG: the financing must be secured and the activity must have a positive economic effect, assessed case by case. §45 AufenthV sets the issuing fee at €100 (€96 to extend).",
    officialUrl: "https://www.make-it-in-germany.com/",
    status: "open",
    source: "https://www.make-it-in-germany.com/en/visa-residence/types/self-employment",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Estonia", code: "EE", flag: "🇪🇪", region: "Europe",
    visaName: "Digital Nomad Visa",
    minMonthlyIncome: "€3,960",
    minAnnualIncome: null,
    govFee: "€120",
    duration: "1 year",
    renewable: false,
    taxBenefits: false,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Means test is stated as €132 per day (€3,960 per month). One of the world's first digital nomad visas. Must reapply after expiry.",
    officialUrl: "https://vm.ee/en/consular-visa-and-travel-information/visa-information/application-long-stay-d-visa",
    status: "open",
    source: "https://vm.ee/en/consular-visa-and-travel-information/visa-information/application-long-stay-d-visa",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Czech Republic", code: "CZ", flag: "🇨🇿", region: "Europe",
    visaName: "Freelancer / Živnostenský list",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: "5,000 CZK",
    duration: "1 year",
    renewable: true,
    taxBenefits: false,
    businessRequired: true,
    insuranceRequired: true,
    notes: "No income threshold; instead CZK 156,500 must be available (50× the subsistence minimum). Requires registration in the Trade Licensing or Commercial Register. Extension costs a further 1,000 CZK.",
    officialUrl: "https://ipc.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-visa/long-term-visa-for-the-purpose-of-doing-business/",
    status: "open",
    source: "https://ipc.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-visa/long-term-visa-for-the-purpose-of-doing-business/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Hungary", code: "HU", flag: "🇭🇺", region: "Europe",
    visaName: "White Card",
    minMonthlyIncome: "€3,000 net",
    minAnnualIncome: null,
    govFee: "~€110",
    duration: "1 year",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "€3,000 net a month must have been reached in each of the 6 months before entry and maintained throughout the stay — a 50% rise on the old threshold. Open to employees of a foreign employer or owners of a profitable foreign business.",
    officialUrl: "https://oif.gov.hu/tajekoztatok/feher-kartya-digitalis-nomad-tartozkodas",
    status: "open",
    source: "https://oif.gov.hu/tajekoztatok/feher-kartya-digitalis-nomad-tartozkodas",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Malta", code: "MT", flag: "🇲🇹", region: "Europe",
    visaName: "Nomad Residence Permit",
    minMonthlyIncome: null,
    minAnnualIncome: "€42,000",
    govFee: "€400 per person",
    duration: "1 year",
    renewable: true,
    taxBenefits: false,
    businessRequired: true,
    insuranceRequired: true,
    notes: "€42,000 gross a year, stated annually only; the older €32,400 applies to applications made before 1 April 2024. Fee is €300 to apply plus €100 for the residence card. English-speaking EU country with full Schengen access.",
    officialUrl: "https://nomad.residencymalta.gov.mt/nomad-eligibility/",
    status: "open",
    source: "https://nomad.residencymalta.gov.mt/nomad-eligibility/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Iceland", code: "IS", flag: "🇮🇸", region: "Europe",
    visaName: "Long-Term Visa (Nominated Work)",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: null,
    duration: "No longer offered",
    renewable: false,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "Iceland's long-term visa for remote workers no longer exists. Stays over 90 days now need a short-term residence permit whose requirements the Directorate of Immigration has not yet published.",
    officialUrl: "https://island.is/en/o/directorate-of-immigration",
    status: "ended",
    endedNote: "Repealed on 13 May 2026 when the new Visa Act (No. 37/2026) came into force.",
    source: "https://island.is/en/o/directorate-of-immigration",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Romania", code: "RO", flag: "🇷🇴", region: "Europe",
    visaName: "Digital Nomad Visa",
    minMonthlyIncome: "3× the Romanian average gross salary",
    minAnnualIncome: null,
    govFee: "€300",
    duration: "1 year",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Income must be at least three times Romania's average gross monthly salary for each of the 6 months before applying and for the whole period of the visa, so the figure moves each year. The €300 long-stay visa fee applies to applications validated from 27 April 2026 (previously €120).",
    officialUrl: "https://eviza.mae.ro/SupportingDocuments",
    status: "open",
    source: "https://eviza.mae.ro/VisaFees",
    verifiedOn: "2026-09-13",
  },
  // LATIN AMERICA
  {
    country: "Costa Rica", code: "CR", flag: "🇨🇷", region: "Latin America",
    visaName: "Rentista Visa",
    minMonthlyIncome: "US$2,500",
    minAnnualIncome: null,
    govFee: null,
    duration: "2 years",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Rentista route under Ley 8764 art. 82: stable monthly income from abroad, stated monthly and in US dollars. Enrolment in CCSS health insurance is required from the grant of residency. The fee sits in a part of the law we could not reach and the DGME fee page is unreachable, so we publish no figure. Foreign-source income exempt from tax.",
    officialUrl: "https://www.migracion.go.cr/",
    status: "open",
    source: "https://www.dhr.go.cr/defensoria_transparente/participacion_ciudadana/migracion_refugio/ley_8764/titulo_vi.pdf",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Mexico", code: "MX", flag: "🇲🇽", region: "Latin America",
    visaName: "Temporary Resident Visa",
    minMonthlyIncome: "680 days of UMA per month",
    minAnnualIncome: null,
    govFee: "US$56",
    duration: "1–4 years",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "Mexico states the test in UMA, not dollars: monthly income free of encumbrances above the equivalent of 680 days of UMA over the last six months. Very affordable and popular with nomads.",
    officialUrl: "https://www.gob.mx/public/tramites/detalleTramite.xhtml?homoclave=SRE-01-033",
    status: "open",
    source: "https://www.gob.mx/public/tramites/detalleTramite.xhtml?homoclave=SRE-01-033",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Brazil", code: "BR", flag: "🇧🇷", region: "Latin America",
    visaName: "Digital Nomad Visa (VITEM XIV)",
    minMonthlyIncome: "$1,500",
    minAnnualIncome: null,
    govFee: "US$100 (US$290 for US passports)",
    duration: "1 year",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Must work for foreign companies or clients. The fee is set per consulate in local currency: US$100 at Brazilian consulates in the USA — US$290 for US passport holders — and €100 in the euro area. US$1,500 a month or US$18,000 in the bank, renewable once at the Federal Police.",
    officialUrl: "https://www.gov.br/mre/",
    status: "open",
    source: "https://www.gov.br/mre/pt-br/consulado-washington/consulate-general-of-brazil-in-washington-dc/digital-nomads",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Colombia", code: "CO", flag: "🇨🇴", region: "Latin America",
    visaName: "V Visa (Visitante) — Digital Nomad",
    minMonthlyIncome: "3× minimum wage (COP 5,252,715)",
    minAnnualIncome: null,
    govFee: "US$239",
    duration: "2 years",
    renewable: false,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "A V (visitor) visa, not an M (migrant) visa. The threshold is three times the legal monthly minimum wage, which is re-set every year: COP 1,750,905 in 2026, so COP 5,252,715 a month (about US$1,350). Fee is US$56 to study the application plus US$183 to issue it; in Europe and Cuba, €44 + €141.",
    officialUrl: "https://www.cancilleria.gov.co/atencion-y-servicio-al-ciudadano/tramites-y-servicios/visa/tipos-de-visa",
    status: "open",
    source: "https://www.cancilleria.gov.co/atencion-y-servicio-al-ciudadano/tramites-y-servicios/visa/costos?field_actividad_ocupacion_target_id=9357&op=Aplicar",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Ecuador", code: "EC", flag: "🇪🇨", region: "Latin America",
    visaName: "Digital Nomad Visa",
    minMonthlyIncome: "3 SBU (US$1,446 in 2026)",
    minAnnualIncome: "36 SBU (US$17,352 in 2026)",
    govFee: "US$320",
    duration: "2 years, renewable once",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Officially 'Rentista para trabajo remoto'. The threshold is indexed to the Salario Básico Unificado, not a fixed dollar amount: 3 SBU a month for the previous three months, or 36 SBU a year. The 2026 SBU is US$482. Fee is US$50 to apply plus US$270 to issue, with reductions from age 65. USD-based economy; up to 3 dependants allowed.",
    officialUrl: "https://www.gob.ec/mremh/tramites/concesion-visa-residencia-temporal-rentista-trabajo-remoto-visa-nomada",
    status: "open",
    source: "https://www.gob.ec/mremh/tramites/concesion-visa-residencia-temporal-rentista-trabajo-remoto-visa-nomada",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Argentina", code: "AR", flag: "🇦🇷", region: "Latin America",
    visaName: "Residencia Transitoria como Nómada Digital",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: "ARS 32,000 (ARS 16,000 Mercosur)",
    duration: "6 months (extendable)",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "A transitory residence under art. 24(h) of Ley 25.871 and DNM Disposición 758/2022, open only to nationals who do not need a tourist visa, and applied for from inside Argentina. The DNM sets no income threshold and requires no insurance. The fee is 32 UMSM extra-Mercosur / 16 UMSM for Mercosur nationals. Affordable with rich culture; Buenos Aires is a top nomad city.",
    officialUrl: "https://www.argentina.gob.ar/servicio/obtener-una-residencia-transitoria-como-nomada-digital",
    status: "open",
    source: "https://www.argentina.gob.ar/servicio/obtener-una-residencia-transitoria-como-nomada-digital",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Panama", code: "PA", flag: "🇵🇦", region: "Latin America",
    visaName: "Visa de Corta Estancia como Trabajador Remoto",
    minMonthlyIncome: "B/.3,000",
    minAnnualIncome: "B/.36,000",
    govFee: "~$300",
    duration: "9 months",
    renewable: true,
    taxBenefits: true,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Decreto Ejecutivo 198 of 7 May 2021. Requires foreign-source income of at least B/.36,000 a year and a monthly income of no less than B/.3,000 — the balboa is pegged 1:1 to the US dollar. A medical insurance policy covering the whole stay must be filed. No income tax on foreign-source income.",
    officialUrl: "https://www.migracion.gob.pa/wp-content/uploads/18.REQUISITOS-PARA-SOLICITAR-VISA-DE-CORTA-ESTANCIA-COMO-TRABAJADOR-REMOTO.pdf",
    status: "open",
    source: "https://www.migracion.gob.pa/wp-content/uploads/18.REQUISITOS-PARA-SOLICITAR-VISA-DE-CORTA-ESTANCIA-COMO-TRABAJADOR-REMOTO.pdf",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Barbados", code: "BB", flag: "🇧🇧", region: "Caribbean",
    visaName: "Barbados Welcome Stamp",
    minMonthlyIncome: "$4,167",
    minAnnualIncome: "$50,000",
    govFee: "$2,000 (single) / $3,000 (family)",
    duration: "1 year",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "Applications and renewals both open, under Form C-5 of the Immigration Act Cap. 190. US$50,000 a year, US$2,000 to apply as an individual or US$3,000 for a family bundle. Health insurance is not among the documents the official application asks for.",
    officialUrl: "https://barbadoswelcomestamp.bb/applynow/",
    status: "open",
    source: "https://barbadoswelcomestamp.bb/applynow/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Cayman Islands", code: "KY", flag: "🇰🇾", region: "Caribbean",
    visaName: "Global Citizen Concierge Programme",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: null,
    duration: "No longer offered",
    renewable: false,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "The Cayman Islands no longer run a remote-work route. Long stays now go through the ordinary immigration framework administered by WORC.",
    officialUrl: "https://gov.ky/w/immigration-reform-guidebook",
    status: "ended",
    endedNote: "Closed. The programme's own site (eworkcayman.com) no longer exists — the domain does not resolve — and the programme appears in no current WORC form or fee schedule.",
    source: "https://gov.ky/w/immigration-reform-guidebook",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Antigua & Barbuda", code: "AG", flag: "🇦🇬", region: "Caribbean",
    visaName: "Nomad Digital Residence",
    minMonthlyIncome: "$4,167",
    minAnnualIncome: "$50,000",
    govFee: "$1,500",
    duration: "2 years",
    renewable: false,
    taxBenefits: true,
    businessRequired: false,
    insuranceRequired: false,
    notes: "Antigua & Barbuda's Nomad Digital Residence is no longer accepting applications.",
    officialUrl: "https://nomad.gov.ag/",
    status: "ended",
    endedNote: "The programme's own government portal announces that it has ended.",
    source: "https://nomad.gov.ag/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Anguilla", code: "AI", flag: "🇦🇮", region: "Caribbean",
    visaName: "Work from Anguilla Program",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: null,
    duration: "1 year",
    renewable: false,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Work from Anguilla no longer appears on any live official page and no official source states a current fee.",
    officialUrl: "https://www.gov.ai/service/immigration-labour-visas-travel",
    status: "ended",
    endedNote: "No longer offered; treat as ended. The nearest current official page is Anguilla's immigration and visas service.",
    source: "https://www.gov.ai/service/immigration-labour-visas-travel",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Bermuda", code: "BM", flag: "🇧🇲", region: "Caribbean",
    visaName: "Work From Bermuda Certificate",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: "$263",
    duration: "1 year",
    renewable: false,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Work From Bermuda has concluded. The successor route is Permission to Reside on an Annual Basis.",
    officialUrl: "https://forms.gov.bm/work-from-bermuda/apply",
    status: "ended",
    endedNote: "Concluded on 28 February 2025; no applications accepted.",
    source: "https://forms.gov.bm/work-from-bermuda/apply",
    verifiedOn: "2026-09-13",
  },
  // MIDDLE EAST & AFRICA
  {
    country: "UAE", code: "AE", flag: "🇦🇪", region: "Middle East",
    visaName: "Remote Work Visa",
    minMonthlyIncome: "US$3,500",
    minAnnualIncome: null,
    govFee: "AED 300–740",
    duration: "1 year",
    renewable: true,
    taxBenefits: true,
    businessRequired: true,
    insuranceRequired: true,
    notes: "US$3,500 a month, stated monthly only. Fees differ by authority: AED 300 through ICP, AED 740 through GDRFA Dubai. Zero income tax; Dubai is a major global nomad hub.",
    officialUrl: "https://u.ae/en/information-and-services/visa-and-emirates-id/Types-of-visas/Residence-visa/residence-visa-for-working-outside-the-uae",
    status: "open",
    source: "https://u.ae/en/information-and-services/visa-and-emirates-id/Types-of-visas/Residence-visa/residence-visa-for-working-outside-the-uae",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Mauritius", code: "MU", flag: "🇲🇺", region: "Africa",
    visaName: "Premium Travel Visa",
    minMonthlyIncome: "US$1,500",
    minAnnualIncome: null,
    govFee: "Free",
    duration: "1 year",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "US$1,500 a month per adult applicant, plus US$500 for each dependent child. No application fee. Beautiful island, English-speaking.",
    officialUrl: "https://passport.govmu.org/",
    status: "open",
    source: "https://edbmauritius.org/wp-content/uploads/2023/12/FAQs-Premium-Visa.pdf",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Cape Verde", code: "CV", flag: "🇨🇻", region: "Africa",
    visaName: "Remote Working Visa",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: "5,000 CVE",
    duration: "6 months, renewable once",
    renewable: true,
    taxBenefits: false,
    businessRequired: true,
    insuranceRequired: true,
    notes: "Not an income test: applicants show an average bank balance of €1,500 (individual) or €2,700 (family). The immigration authority lists a 5,000 CVE fee; Turismo de Cabo Verde separately lists €20 per person plus a one-off €34 airport fee, and the two official sources conflict.",
    officialUrl: "https://e-portaldef.gov.cv/nomadas-digitais",
    status: "open",
    source: "https://e-portaldef.gov.cv/nomadas-digitais",
    verifiedOn: "2026-09-13",
  },
  {
    country: "South Africa", code: "ZA", flag: "🇿🇦", region: "Africa",
    visaName: "Remote Work Visa",
    minMonthlyIncome: null,
    minAnnualIncome: "R650,796",
    govFee: null,
    duration: "3 months to 3 years",
    renewable: false,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "In force since 9 October 2024 under section 11(1)(b)(iv) and offered at South African missions. Gross salary of R650,796 a year, proven with three months' bank statements. The holder may not take up employment in South Africa, and SARS registration is required beyond 183 days.",
    officialUrl: "https://www.dha.gov.za/images/notices/8october24/Remote_Work_Visa_-_requirements_-_9_Oct_2024.pdf",
    status: "open",
    source: "https://www.dha.gov.za/images/notices/8october24/Remote_Work_Visa_-_requirements_-_9_Oct_2024.pdf",
    verifiedOn: "2026-09-13",
  },
  // ASIA & PACIFIC
  {
    country: "Malaysia", code: "MY", flag: "🇲🇾", region: "Asia",
    visaName: "DE Rantau Nomad Pass",
    minMonthlyIncome: null,
    minAnnualIncome: "US$24,000 (tech) / US$60,000",
    govFee: "RM 1,080",
    duration: "3–12 months, renewable to 24 months",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Income is stated in US dollars, not ringgit: US$24,000 a year for tech professions, US$60,000 for non-tech. Fee is RM 1,080 including SST, plus RM 540 per dependent and the immigration pass fee (RM 90 per 3 months). MDEC's FAQ is at version 10.0, dated 28 August 2026.",
    officialUrl: "https://www.mdec.my/derantau",
    status: "open",
    source: "https://www.mdec.my/api/media/file/DE-Rantau_Pass_FAQ_v10.pdf",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Thailand", code: "TH", flag: "🇹🇭", region: "Asia",
    visaName: "Long-Term Resident (LTR) Visa",
    minMonthlyIncome: null,
    minAnnualIncome: "US$80,000",
    govFee: "THB 50,000",
    duration: "10 years",
    renewable: true,
    taxBenefits: true,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Remote workers apply under the LTR 'Work-from-Thailand Professionals' category: 10 years as 5 years plus a 5-year extension. BOI states an annual average of US$80,000 and no monthly figure. A work permit is NOT granted to this category, and the 17% flat tax applies only to Highly-skilled Professionals. Requires an employment contract with a listed company, or a private company trading 3+ years with US$50 million combined revenue over 3 years.",
    officialUrl: "https://ltr.boi.go.th/",
    status: "open",
    source: "https://ltr.boi.go.th/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Indonesia (Bali)", code: "ID", flag: "🇮🇩", region: "Asia",
    visaName: "Remote Worker Visa (E33G) / Second Home (E33E)",
    minMonthlyIncome: null,
    minAnnualIncome: "US$60,000",
    govFee: "IDR 7,000,000",
    duration: "1 year, extendable (E33G)",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "The remote-worker route is index E33G: US$60,000 a year plus a minimum US$2,000 bank balance over the last 3 months, for 1 year, extendable. The second-home route is E33E, 5 years extendable to 10. Bali is one of the world's top nomad hubs.",
    officialUrl: "https://www.imigrasi.go.id/wna/daftar-visa-indonesia/E33G",
    status: "open",
    source: "https://www.imigrasi.go.id/wna/daftar-visa-indonesia/E33G",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Japan", code: "JP", flag: "🇯🇵", region: "Asia",
    visaName: "Designated Activities (Digital Nomad)",
    minMonthlyIncome: null,
    minAnnualIncome: "¥10,000,000",
    govFee: "¥15,000",
    duration: "6 months",
    renewable: false,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Six-month stay, no extension: holders must leave and wait six months before reapplying, and no residence card is issued. Open to nationals of 51 listed countries and regions. The ¥15,000 single-entry fee applies to applications accepted from 1 July 2026.",
    officialUrl: "https://www.moj.go.jp/isa/applications/status/designatedactivities53_00001.html",
    status: "open",
    source: "https://www.moj.go.jp/isa/applications/status/designatedactivities53_00001.html",
    verifiedOn: "2026-09-13",
  },
  {
    country: "South Korea", code: "KR", flag: "🇰🇷", region: "Asia",
    visaName: "Workation (Digital Nomad) Visa, F-1-D",
    minMonthlyIncome: null,
    minAnnualIncome: "KRW 52.4M–104.8M",
    govFee: "Varies by nationality",
    duration: "1 year, extendable to 3 years",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Permanent from 30 June 2026 after a 2.5-year pilot that issued 743 visas. The income test is tiered against the prior year's GNI per capita (KRW 52,416,000 for 2025): 1.5× or 1× for ages 18–34 depending on region, 2× or 1.5× for ages 35 and over, with the higher band applying inside the Seoul metropolitan area or when family accompany. Also requires a year in the same industry and medical insurance covering at least KRW 100 million.",
    officialUrl: "https://www.immigration.go.kr/bbs/moj/182/496858/download.do",
    status: "open",
    source: "https://www.immigration.go.kr/bbs/moj/182/496858/download.do",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Vietnam", code: "VN", flag: "🇻🇳", region: "Asia",
    visaName: "E-Visa / Long Stay Visa",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: "US$25 single / US$50 multiple",
    duration: "Up to 90 days",
    renewable: false,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: false,
    notes: "Vietnam still has no dedicated nomad visa. The e-visa is capped at 90 days, single or multiple entry, and the immigration portal describes no extension or renewal — a longer stay means a new visa obtained through a Vietnamese inviting or guaranteeing party. Very affordable.",
    officialUrl: "https://evisa.xuatnhapcanh.gov.vn/",
    status: "open",
    source: "https://evisa.xuatnhapcanh.gov.vn/en_US/web/guest/khai-thi-thuc-dien-tu/cap-thi-thuc-dien-tu",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Philippines", code: "PH", flag: "🇵🇭", region: "Asia",
    visaName: "Digital Nomad Visa (Executive Order 86)",
    minMonthlyIncome: null,
    minAnnualIncome: null,
    govFee: null,
    duration: "Up to 1 year, renewable",
    renewable: true,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "The Philippines created a real nomad visa by Executive Order No. 86, signed 24 April 2025 and issued by the Department of Foreign Affairs, not the Bureau of Immigration. Applicants must be 18 or over, prove remote work for clients or employers abroad and sufficient foreign-sourced income, hold health insurance valid for the whole visa, have no criminal record, and be a national of a country that both offers nomad visas to Filipinos and hosts a Philippine Foreign Service Post. No employment in the Philippines is allowed. EO 86 states no income figure and no fee. Important: we could not confirm from any official source that the DFA has started issuing these visas — the order required implementing guidelines within 30 days, and the DFA has published no verifiable application page.",
    officialUrl: "https://elibrary.judiciary.gov.ph/thebookshelf/showdocs/5/98965",
    status: "open",
    source: "https://elibrary.judiciary.gov.ph/thebookshelf/showdocs/5/98965",
    verifiedOn: "2026-09-13",
  },
  // AMERICAS
  {
    country: "Costa Rica", code: "CR", flag: "🇨🇷", region: "Latin America",
    visaName: "Digital Nomad Visa",
    minMonthlyIncome: "$3,000",
    minAnnualIncome: null,
    govFee: "$100",
    duration: "1 year",
    renewable: true,
    taxBenefits: true,
    businessRequired: false,
    insuranceRequired: true,
    notes: "Ley 10008 and its Reglamento (Decreto 43619 H-MGP-TUR). US$3,000 a month, or US$4,000 if dependants are included. Beyond the US$100 application fee there is a further US$90 for the residency document. Insurance must cover the whole stay with at least US$50,000 of cover. Article 16 grants full exemption from income tax on foreign earnings.",
    officialUrl: "https://migracion.go.cr/nomadas-digitales/",
    status: "open",
    source: "https://migracion.go.cr/nomadas-digitales/",
    verifiedOn: "2026-09-13",
  },
  {
    country: "Belize", code: "BZ", flag: "🇧🇿", region: "Latin America",
    visaName: "Work Where You Vacation Program",
    minMonthlyIncome: null,
    minAnnualIncome: "US$75,000 (US$100,000 for families)",
    govFee: "BZD 500 per adult",
    duration: "Up to 180 days",
    renewable: false,
    taxBenefits: false,
    businessRequired: false,
    insuranceRequired: true,
    notes: "The official threshold is annual and far higher than commonly listed: US$75,000 a year for an individual, US$100,000 for couples and families. Fee is BZD 500 per adult plus BZD 200 per child under 18. Travel insurance with at least US$50,000 of cover is required. The programme page states a hard 180-day maximum and says nothing about renewal, so we do not claim one. English-speaking, Caribbean coast and jungle.",
    officialUrl: "https://www.travelbelize.org/work-where-you-vacation/",
    status: "open",
    source: "https://www.travelbelize.org/work-where-you-vacation/",
    verifiedOn: "2026-09-13",
  },
];

export const digitalNomadVisas: DigitalNomadVisa[] = ALL_NOMAD_VISAS.filter(
  (v, i, arr) => arr.findIndex((x) => x.code === v.code && x.visaName === v.visaName) === i,
);

export const NOMAD_REGIONS = ["All", "Europe", "Latin America", "Caribbean", "Asia", "Middle East", "Africa"];

export * from "./siteNav";

export * from "./commonsImage";

export * from "./visaStatus";
export * from "./designTokens";
export * from "./entryRequirements";
