#!/usr/bin/env node
// Writes the shared design tokens to a CSS file the React app can @import.
//
//   node scripts/gen-tokens.mjs          write artifacts/visa-checker/src/tokens.generated.css
//   node scripts/gen-tokens.mjs --check  exit 1 if the checked-in file is stale (CI)
//
// Why a generated file: CSS cannot import a TypeScript string, and the tokens
// live in lib/travel-data so the server-rendered pages and the app read ONE
// definition. Generate-then-verify-clean is boring and cannot silently drift —
// which is the point, because this repo has shipped server/app drift bugs
// three times.
import { build } from "../artifacts/api-server/node_modules/esbuild/lib/main.js";
import { mkdtempSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "artifacts/visa-checker/src/tokens.generated.css");
const check = process.argv.includes("--check");

// Bundle the package entry to a temp ESM file so plain Node can import it
// (the package ships raw .ts with extensionless relative imports).
const tmp = join(mkdtempSync(join(tmpdir(), "tokens-")), "travel-data.mjs");
await build({
  entryPoints: [join(root, "lib/travel-data/src/index.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  outfile: tmp,
  logLevel: "error",
});
const { APP_TOKENS_CSS } = await import(pathToFileURL(tmp).href);

const css =
  `/* GENERATED by scripts/gen-tokens.mjs from lib/travel-data/src/designTokens.ts.\n` +
  `   Do not edit: run \`pnpm run tokens\`. The deploy fails if this file is stale.\n   App subset only (see APP_TOKENS_CSS): never redefines a shadcn variable. */\n` +
  `${APP_TOKENS_CSS}\n`;

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== css) {
    console.error(`tokens.generated.css is stale — run \`pnpm run tokens\` and commit the result.`);
    process.exit(1);
  }
  console.log("tokens.generated.css is up to date");
} else {
  writeFileSync(OUT, css);
  console.log(`wrote ${OUT} (${css.length} bytes)`);
}
